name: better_gtask
description: Better Google Tasks
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  googleapis: ^11.4.0
  go_router: ^12.0.0
  flutter_riverpod: ^2.4.4
  riverpod_annotation: ^2.2.1
  google_sign_in: ^6.1.5
  extension_google_sign_in_as_googleapis_auth: ^2.0.11
  freezed_annotation: ^2.4.1
  very_good_infinite_list: ^0.7.1
  firebase_core: ^2.20.0
  sign_button: ^2.0.6
  uuid: ^4.1.0
  isar: ^4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  go_router_builder: ^2.3.4
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.3.5
  freezed: ^2.4.5

flutter:
  uses-material-design: true